### ISSUE TITLE
About workflows

### ISSUE THREAD

**Issue by mkz212** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#111]
@embee8 @jandersonhill 

I suggest the following workflows:

### Disable workflows:
- check versions - admin should chose version, not user adding PR, and not for all PR there should be new version (e.g. readme, workflows etc). 
- tag commit - changelog should be given in github releases, additionally also could be in changelog.md

https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow

### Lint and compile. 
- It is ok as it is now. To check new PR. This ensures that the new PR are well pre-prepared.

### Publish

- One workflow. 
- Automatically detect: for public take version and changelog from newest github release not marked as prerelease, for beta take version and changelog from newest github release with tag Pre-release. 
- Workflow starts automatically after adding github release,  automatically get version from github release tag. Github tag starts with v. E.G v1.8.5 , nmp version is 1.8.5. So we need to add function to remove v or simply tag releases without v (v is added in UI). 
- I think it's the best and simplest option. It provides a lot of control over the releases. And at the same time it solves many problems.

Workflow: https://github.com/mkz212/homebridge-panasonic-ac-platform/issues/3

### Changelog - from where is it taken
- before a user updates the plugin, the release notes from the latest github release (newest release with tag latest) will be pulled (it ignores releases marked as pre-release)
- any `CHANGELOG.md` file is displayed after a user updates a plugin
- the UI does not show release notes for beta versions (for homebridge, UI, nor any plugins)

**Comment by mkz212** [comment]
A few examples of how I imagine the update process.

In each case, at the beginning we have:
- adding PR (one or several, by one person or several). Every PR checked by lint and compile. There is no requirement to give a version here!
- possible corrections to PRs
- merge all or selected PRs



### Examples for publish latest -> latest

### 1.8.4 -> 1.8.5
- admin add new github release with tag 1.8.5 and changelog, not check this as pre-release
- run workflow: publish latest. If it starts the workflow and no new github release is added then the workflow will show a error

### 1.8.4 -> 1.9.0
Just like before.
- admin add new github release with tag 1.9.0 and changelog, not check this as pre-release
- run workflow: publish latest. If it starts the workflow and no new github release is added then the workflow will show a error


### Example for publish latest -> beta

### 1.8.4 -> 1.8.5-beta.0
- admin add new github release with tag 1.8.5-beta.0 and changelog, check this as pre-release
- run workflow: publish beta. If it starts the workflow and no new github release is added then the workflow will show a error

### Example for publish beta -> beta

### 1.8.5-beta.0 -> 1.8.5-beta.1
- admin add new github release with tag 1.8.5-beta.1 and changelog, check this as pre-release
- run workflow: publish beta. If it starts the workflow and no new github release is added then the workflow will show a error


### Example for publish beta -> latest

### 1.8.5-beta.3 -> 1.8.5
- admin add new github release with tag 1.8.5 and changelog, not check this as pre-release
- run workflow: publish latest. If it starts the workflow and no new github release is added then the workflow will show a error

**Comment by mkz212** [comment]
Here is also good example: https://dev.to/astagi/publish-to-npm-using-github-actions-23fn . It publish to npm automatically when you create new github release.

**Comment by mkz212** [comment]
And here is probably even a ready solution: https://stackoverflow.com/questions/59518658/how-to-use-github-release-version-number-in-github-action

**Comment by mkz212** [comment]
```

name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Version
        run: npm version ${{ github.event.release.tag_name }}
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

```

**Comment by mkz212** [comment]
```
# Creates a new beta release and publishes it to npm.

# The release will be marked as 'pre-release'
# on GitHub and carry the 'beta' tag on npm.

name: Create and publish beta release

on:
  release:
    types: [published]

jobs:
  create-release:
    name: Create beta release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{secrets.GH_CLI_TOKEN}}
        run: |
          echo "The beta release version will be: ${{secrets.npm_token}}"
          
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        # The prepublishOnly script lints and builds the project (see package.json)
        run: |
          npm version ${{ github.event.release.tag_name }}
          npm ci
          npm publish --tag beta

```

**Comment by mkz212** [comment]
FOR LATEST:  ( ??? )

```
# Creates a new production release and publishes it to npm.

# The release will be marked as 'latest release'
# on GitHub and carry the 'latest' tag on npm.

name: Create and publish production release

on:
  release:
    types: [published]

jobs:
  if: "!github.event.release.prerelease"
  create-release:
    name: Create production release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Show summary
        env:
          GITHUB_TOKEN: ${{secrets.GH_CLI_TOKEN}}
        run: |
          echo "The public release version will be: ${{ github.event.release.tag_name }}"

      - name: Check if (beta) version exists on npm
        id: check-beta
        run: |
          version=${{ github.event.release.tag_name }}
          package_exists=$(npm view .@$version version | wc -l | tr -d ' ')
          echo "package_exists=$package_exists" >> "$GITHUB_OUTPUT"

      - name: Publish to npm
        if: ${{ steps.check-beta.outputs.package_exists == 0}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        # The prepublishOnly script lints and builds the project (see package.json)
        run: |
          npm version ${{ github.event.release.tag_name }}
          npm ci
          npm publish

      - name: Tag existing version with 'latest'
        if: ${{ steps.check-beta.outputs.package_exists > 0 }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          version=${{ github.event.release.tag_name }}
          npm dist-tag add homebridge-panasonic-ac-platform@$version latest
          npm dist-tag rm homebridge-panasonic-ac-platform@$version beta

```

**Comment by mkz212** [comment]
Note: The prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.

**Comment by mkz212** [comment]
Github tag starts with v. E.g v1.8.5. NPM version is 1.8.5. So we need to remove v .

**Comment by jandersonhill** [comment]
Cool. I'm out today and tomorrow; I'll try to take a look at the workflow later in the week. Looks like you've done the hard work!

**Comment by mkz212** [comment]
> Cool. I'm out today and tomorrow; I'll try to take a look at the workflow later in the week. Looks like you've done the hard work!

Hard work did here @embee8 because in the majority it is his workflow - I only slightly changed so that they were launched after adding github release and get versions from it. But I'm not 100% sure if they work well yet. But I'm sure it can't be easier - you merge selected PRs and add github release when you want to publish new version and that's all.

**Comment by mkz212** [comment]
Or maybe it's even better to have one workflow?
- will start automatically when github releas is added
- will detect whether latest or beta


```
# Creates a new latest / beta release and publishes it to npm.

name: Create and publish latest /  beta release

on:
  release:
    types: [published]

jobs:
  create-release:
    
    name: Create latest / release
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Show summary
        env:
          GITHUB_TOKEN: ${{secrets.GH_CLI_TOKEN}}
        run: |
          echo "The release version will be: ${{ github.event.release.tag_name }}"
          

 # BETA

      - name: Publish to npm - beta
        if: "github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        # The prepublishOnly script lints and builds the project (see package.json)
        run: |
          npm version ${{ github.event.release.tag_name }}
          npm ci && npm run build
          npm publish --tag beta

# LATEST

      - name: Check if (beta) version exists on npm
        if: "!github.event.release.prerelease"
        id: check-beta
        run: |
          version=${{ github.event.release.tag_name }}
          package_exists=$(npm view .@$version version | wc -l | tr -d ' ')
          echo "package_exists=$package_exists" >> "$GITHUB_OUTPUT"

      - name: Publish to npm
        if: "!github.event.release.prerelease"
        if: ${{ steps.check-beta.outputs.package_exists == 0}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        # The prepublishOnly script lints and builds the project (see package.json)
        run: |
          npm version ${{ github.event.release.tag_name }}
          npm ci && npm run build
          npm publish

      - name: Tag existing version with 'latest'
        if: ${{ !github.event.release.prerelease && steps.check-beta.outputs.package_exists > 0 }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          version=${{ github.event.release.tag_name }}
          npm dist-tag add homebridge-panasonic-ac-platform@$version latest
          npm dist-tag rm homebridge-panasonic-ac-platform@$version beta

```
